Revancify X: rebrand and refactor some code

diff --git a/revx b/revx
--- a/revx
+++ b/revx
@@ -3,8 +3,8 @@
 HOME=/data/data/com.termux/files/home
 BIN=/data/data/com.termux/files/usr/bin
 
-path="$HOME/Revancify"
-cp "$path/revancify" "$BIN/revancify" >/dev/null 2>&1
+path="$HOME/RevancifyX"
+cp "$path/revx" "$BIN/revx" &> /dev/null
 
 help() {
     if [ "$1" == "1" ]; then
@@ -18,15 +18,15 @@ help() {
         IFS=","
         echo -e "\e[1;31mInvalid Argument(s) Passed: ${invalidArgs[*]}\n\e[0m"
     fi
-    echo -e "\e[1;34mrevancify\n\e[0m
-\e[1;33mUsage:\e[0m \e[1;32mrevancify [OPTION]\n\e[0m
+    echo -e "\e[1;34mrevancify X\n\e[0m
+\e[1;33mUsage:\e[0m \e[1;32mrevancify X[OPTION]\n\e[0m
 \e[1;33mOptions:\e[0m
 \e[1;33m-n, --no-root     \e[1;34mRun without SU permissions\e[0m
 \e[1;33m-o, --offline     \e[1;34mRun without updating revancify\e[0m
 \e[1;33m-r, --reinstall   \e[1;34mReinstall revancify\e[0m
 \e[1;33m-h, --help        \e[1;34mPrints help statement\e[0m
 
-\e[1;35mGithub repo: https://github.com/kastentop2005/Revancify"
+\e[1;35mGithub repo: https://github.com/kastentop2005/Revancify-X"
     exit "$1"
 }
 
@@ -46,8 +46,8 @@ do
                         shift
                         ;;
     "-r" | "--reinstall")
-                        if ping -c 1 google.com >/dev/null 2>&1; then
-                            cd "$path"/.. && rm -rf "$path" && git clone --depth=1 https://github.com/decipher3114/Revancify.git && revancify && exit
+                        if ping -c 1 google.com &> /dev/null; then
+                            cd "$path"/.. && rm -rf "$path" && git clone --depth=1 https://github.com/kastentop2005/Revancify-X && revx && exit
                         else
                             echo "No internet Connection !!"
                             exit 1
@@ -70,20 +70,20 @@ if [ "$(getprop ro.product.cpu.abi)" = "armeabi-v7a" ]; then
     echo "You may get build errors."
     read -N 1 -s -r -p $'Press ENTER to CONTINUE or SPACE to EXIT...\n' key
     if [ "$key" = " " ]; then
-        echo "Script terminated"
+        echo "Revancify X has been terminated"
         exit
     fi
 fi
 
 terminate() {
     clear
-    echo "Script terminated !!"
+    echo "Revancify X has been terminated"
     tput cnorm
     exit 1
 }
 trap terminate SIGTERM SIGINT SIGABRT
 
-DATA="$HOME/revancify-data"
+DATA="$HOME/RevancifyX-data"
 [ ! -d $DATA ] && mkdir -p "$DATA"
 # shellcheck source=/dev/null
 source "$DATA/.envVars" > /dev/null 2>&1
@@ -91,14 +91,14 @@ source "$DATA/.envVars" > /dev/null 2>&1
 export DIALOGRC="$path/configs/.dialogrc$theme"
 
 checkdependencies() {
-    if [ -f "$BIN/aapt2" ] && [ -f "$BIN/pup" ] && bins=$(ls "$BIN") && grep -q java <<<"$bins" && grep -q wget <<<"$bins" && grep -q tput <<<"$bins" && grep -q dialog <<<"$bins" && grep -q jq <<<"$bins" && ls "$BIN/revancify" >/dev/null 2>&1 && ls "$HOME/storage" >/dev/null 2>&1; then
+    if command -v aapt2 pup java wget tput dialog jq revancify &> /dev/null; then
         return 0
     else
-        if ping -c 1 google.com >/dev/null 2>&1; then
-            installdependencies || (echo "Dependencies not installed !!" && exit 1)
+        if ping -c 1 google.com &> /dev/null; then
+            installdependencies || (echo "Dependencies are not installed" && exit 1)
         else
-            cp "$path/revancify" "$BIN/revancify"
-            echo -e "Dependencies not installed !!\nRun again with internet connection."
+            cp "$path/revx" "$BIN/revx"
+            echo -e "Dependencies are not installed\nRun the program again with internet connection"
             exit 1
         fi
     fi
@@ -131,7 +131,7 @@ installdependencies() {
         echo "pup is already installed. Skipping..."
     fi
 
-    echo "Dependencies installed successfully."
+    echo "Dependencies have been installed successfully"
     return 0
 }
 
@@ -141,23 +141,23 @@ checkrevancify() {
         rm -rf ./*cache*
         return 0
     else
-        echo -e "\e[1;31mRevancify dir is not found !!\e[0m"
-        echo -e "\e[1;31mDo you want to reinstall Revancify?\e[0m"
+        echo -e "\e[1;31mRevancify X dir hasn't been found\e[0m"
+        echo -e "\e[1;31mDo you want to reinstall Revancify X?\e[0m"
         read -r -p "[Y/N]: " choice
         case "$choice" in
         y | Y)
             rm -rf "$path"
-            git clone --depth=1 https://github.com/kastentop2005/Revancify.git && revancify && exit
+            git clone --depth=1 https://github.com/kastentop2005/Revancify-X && revx && exit
             ;;
         n | N)
-            echo "Removing revancify completely !!"
+            echo "Removing Revancify X..."
             sleep 0.5s
-            rm "$BIN/revancify"
-            echo "Successfully Uninstalled revancify."
+            rm "$BIN/revx"
+            echo "Successfully uninstalled"
             exit 0
             ;;
         ?)
-            echo "Invalid option !!"
+            echo "Invalid choice!"
             exit 1
             ;;
         esac
@@ -167,7 +167,7 @@ checkrevancify() {
 checkdependencies
 checkrevancify
 tput civis
-dialog --keep-window --no-shadow --keep-window --infobox "\n  █▀█ █▀▀ █░█ ▄▀█ █▄░█ █▀▀ █ █▀▀ █▄█\n  █▀▄ ██▄ ▀▄▀ █▀█ █░▀█ █▄▄ █ █▀░ ░█░  \n\nDeveloper    : decipher\nLast Updated : Checking...\nStatus       : Checking..." 10 42
+dialog --keep-window --no-shadow --keep-window --infobox "\n  █▀█ █▀▀ █░█ ▄▀█ █▄░█ █▀▀ █ █▀▀ █▄█\n  █▀▄ ██▄ ▀▄▀ █▀█ █░▀█ █▄▄ █ █▀░ ░█░  \n\nDeveloper    : konnlori\nLast Updated : Checking...\nStatus       : Checking..." 10 42
 
 if ping -c 1 google.com >/dev/null 2>&1; then
     status=${status:-Online}
@@ -176,9 +176,9 @@ else
 fi
 if [ "$status" == "Online" ]; then
     git pull >/dev/null 2>&1 || (git fetch --all >/dev/null 2>&1 && git reset --hard "@{u}" >/dev/null 2>&1)
-    dialog --no-shadow --infobox "\n  █▀█ █▀▀ █░█ ▄▀█ █▄░█ █▀▀ █ █▀▀ █▄█\n  █▀▄ ██▄ ▀▄▀ █▀█ █░▀█ █▄▄ █ █▀░ ░█░  \n\nDeveloper    : decipher\nLast Updated : $(git log -1 --pretty='format:%cd' --date=format:'%b %d, %Y | %H:%M')\nStatus       : $status" 10 42
+    dialog --no-shadow --infobox "\n  █▀█ █▀▀ █░█ ▄▀█ █▄░█ █▀▀ █ █▀▀ █▄█\n  █▀▄ ██▄ ▀▄▀ █▀█ █░▀█ █▄▄ █ █▀░ ░█░  \n\nDeveloper    : konnlori\nLast Updated : $(git log -1 --pretty='format:%cd' --date=format:'%b %d, %Y | %H:%M')\nStatus       : $status" 10 42
 else
-    dialog --no-shadow --infobox "\n  █▀█ █▀▀ █░█ ▄▀█ █▄░█ █▀▀ █ █▀▀ █▄█\n  █▀▄ ██▄ ▀▄▀ █▀█ █░▀█ █▄▄ █ █▀░ ░█░  \n\nDeveloper    : decipher\nLast Updated : $(git log -1 --pretty='format:%cd' --date=format:'%b %d, %Y | %H:%M')\nStatus       : $status" 10 42
+    dialog --no-shadow --infobox "\n  █▀█ █▀▀ █░█ ▄▀█ █▄░█ █▀▀ █ █▀▀ █▄█\n  █▀▄ ██▄ ▀▄▀ █▀█ █░▀█ █▄▄ █ █▀░ ░█░  \n\nDeveloper    : konnlori\nLast Updated : $(git log -1 --pretty='format:%cd' --date=format:'%b %d, %Y | %H:%M')\nStatus       : $status" 10 42
 fi
 cd "$DATA" >/dev/null 2>&1 || true
 bash "$path/main.sh" "$flag"
@@ -186,9 +186,9 @@ exitstatus=$?
 clear
 cd "$HOME" || :
 if [ $exitstatus -eq 0 ]; then
-    echo "Revancify has been exited"
+    echo "Exited Revancify X"
 else
-    echo "Revancify has been terminated"
+    echo "Revancify X has been terminated"
     rm -rf -- *cache >/dev/null 2>&1
 fi
 tput cnorm
